import React from "react";
import MaterialReactTable from 'material-react-table';
import { Box, Typography, IconButton } from '@mui/material';
import { Lightbulb as LightBulbIcon } from '@mui/icons-material';



const paperData = [
  {
    "Paper_ID": 146382.0,
    "Title": "A three-dimensional/stereoscopic display and model control system for Great Lakes forecasts",
    "Date_Published": 1990.0,
    "Abstract": "A forecasting system for the Great Lakes in which the data generated by a three-dimensional numerical model is visualized by a 3-D/stereoscopic display module is discussed. The module consists of a control panel and a display window with the capability of interactively rendering the results. The event scheduling for scenario testing to steer the 3-D numerical model is achieved by a similar panel. These panels set up the simulation and control the data flow between the graphics workstation and supercomputer. Rendering methods, stereo imagery, and animation are incorporated to display the results. Interaction between the user, the workstation, and the supercomputer allows steering of the simulation and tracing of the simulation output. Distributed software for postprocessing and volume rendering are used to enhance the representation.<\n<ETX xmlns:mml=\"http://www.w3.org/1998/Math/MathML\" xmlns:xlink=\"http://www.w3.org/1999/xlink\">&gt;</ETX>",
    "Author_Keywords": null,
    "Track": "Vis",
    "Award_Type": null,
    "Award": false,
    "Number_Authors": 4.0,
    "Number_references": 12.0,
    "Times_Cited": 4.0,
    "IEEE_Keywords": "Three dimensional displays,Control system synthesis,Numerical models,Workstations,Supercomputers,Rendering (computer graphics),Lakes,Data visualization,Computer graphics,Testing",
    "Authors": "Chieh-Cheng J. Yen, Keith W. Bedford, Keith W. Bedford, Robert E. Marshall"
  },
  {
    "Paper_ID": 175782.0,
    "Title": "The asymptotic decider: resolving the ambiguity in marching cubes",
    "Date_Published": 1991.0,
    "Abstract": "A method for computing isovalue or contour surfaces of a trivariate function is discussed. The input data are values of the trivariate function, F/sub ijk/, at the cuberille grid points (x/sub i/, y/sub j/, z/sub k/), and the output of a collection of triangles representing the surface consisting of all points where F(x,y,z) is a constant value. The method is a modification that is intended to correct a problem with a previous method.<\n<ETX xmlns:mml=\"http://www.w3.org/1998/Math/MathML\" xmlns:xlink=\"http://www.w3.org/1999/xlink\">&gt;</ETX>",
    "Author_Keywords": null,
    "Track": "Vis",
    "Award_Type": null,
    "Award": false,
    "Number_Authors": 2.0,
    "Number_references": 16.0,
    "Times_Cited": 181.0,
    "IEEE_Keywords": "Isosurfaces,Computer science,Interpolation,Assembly",
    "Authors": "Gregory M. Nielson, Bernd Hamann"
  },
  {
    "Paper_ID": 175804.0,
    "Title": "Multi-valued volumetric visualization",
    "Date_Published": 1991.0,
    "Abstract": "Effective methods for visualizing several sets of volumetric data simultaneously are presented. The methods involve the composition of multiple volumetric rendering techniques. These techniques include contour curves, color-blended contour regions, projection graphs on surfaces, isovalue surface construction, and hypersurface projection graphs.<\n<ETX xmlns:mml=\"http://www.w3.org/1998/Math/MathML\" xmlns:xlink=\"http://www.w3.org/1999/xlink\">&gt;</ETX>",
    "Author_Keywords": null,
    "Track": "Vis",
    "Award_Type": null,
    "Award": false,
    "Number_Authors": 2.0,
    "Number_references": 23.0,
    "Times_Cited": 5.0,
    "IEEE_Keywords": "Data visualization,Displays,Mesh generation,Scattering,Interpolation,Sea surface,Computer science,Geology,Geologic measurements,Sea measurements",
    "Authors": "Thomas A. Foley, David A. Lane"
  },
  {
    "Paper_ID": 175837.0,
    "Title": "Visualization in computational fluid dynamics: a case study",
    "Date_Published": 1991.0,
    "Abstract": "VISUAL 3, a highly interactive environment for the visualization of 3D volumetric scientific data, is described. The volume can be broken up in a structured or unstructured manner, and the problem can be static or unsteady in time. Because the data are volumetric and all the information can be changing, traditional CAD techniques are not appropriate. Therefore, VISUAL3 was developed using intermediate mode-rendering methods. A unique aspect of VISUAL3 is the dimensional windowing approach coupled with cursor mapping, which allows efficient pointing in 3D space. VISUAL3 is composed of a large number of visualization tools that can be generally classified into identification, scanning, and probing techniques.<\n<ETX xmlns:mml=\"http://www.w3.org/1998/Math/MathML\" xmlns:xlink=\"http://www.w3.org/1999/xlink\">&gt;</ETX>",
    "Author_Keywords": null,
    "Track": "Vis",
    "Award_Type": null,
    "Award": false,
    "Number_Authors": 2.0,
    "Number_references": 8.0,
    "Times_Cited": 10.0,
    "IEEE_Keywords": "Computational fluid dynamics,Computer aided software engineering,Workstations,Data visualization,Hardware,Space technology,Graphics,Computer displays,Computer science education,Packaging",
    "Authors": "Robert Haimes, Dave Darmofal"
  },
  {
    "Paper_ID": 235197.0,
    "Title": "Automated design of virtual worlds for visualizing multivariate relations",
    "Date_Published": 1992.0,
    "Abstract": "Interactive visualization systems provide a powerful means to explore complex data, especially when coupled with 3-D interaction and display devices to produce virtual worlds. While designing a quality static 2-D visualization is already a difficult task for most users, designing an interactive 3-D one is even more challenging. To address this problem, AutoVisual, a research system that designs interactive virtual worlds for visualizing and exploring multivariate relations of arbitrary arity, is being developed. AutoVisual uses worlds within worlds, an interactive visualization technique that exploits nested, heterogeneous coordinate systems to map multiple variables onto each spatial dimension. AutoVisual's designs are guided by user-specified visualization tasks, and by a catalog of design principles encoded using a rule-based language.<\n<ETX xmlns:mml=\"http://www.w3.org/1998/Math/MathML\" xmlns:xlink=\"http://www.w3.org/1999/xlink\">&gt;</ETX>",
    "Author_Keywords": null,
    "Track": "Vis",
    "Award_Type": null,
    "Award": false,
    "Number_Authors": 2.0,
    "Number_references": 11.0,
    "Times_Cited": 9.0,
    "IEEE_Keywords": "Data visualization,Graphics,Encoding,Input variables,Computer science,Computer displays,Hardware,User interfaces,Three dimensional displays,Data gloves",
    "Authors": "Clifford Beshers, Steven Feiner"
  },
  {
    "Paper_ID": 235231.0,
    "Title": "Towards a comprehensive volume visualization system",
    "Date_Published": 1992.0,
    "Abstract": "The VolVis system has been developed to satisfy the diverse requirements of the volume visualization community by comfortably housing numerous visualization algorithms and methods within a consistent and well organized framework. The VolVis system is supported by a generalized abstract model which provides for both geometric and volumetric constructs. VolVis contains several rendering algorithms that span the speed versus accuracy continuum. A fast volume rendering algorithm has been developed, which is capable of exploiting existing graphics hardware without placing any viewing restrictions or compromising accuracy. In addition, VolVis includes a volumetric navigation facility, key-frame animation generator, quantitative analysis tools, and a generalized protocol for communicating with 3D input devices.<\n<ETX xmlns:mml=\"http://www.w3.org/1998/Math/MathML\" xmlns:xlink=\"http://www.w3.org/1999/xlink\">&gt;</ETX>",
    "Author_Keywords": null,
    "Track": "Vis",
    "Award_Type": null,
    "Award": false,
    "Number_Authors": 3.0,
    "Number_references": 16.0,
    "Times_Cited": 31.0,
    "IEEE_Keywords": "Rendering (computer graphics),Data visualization,Graphics,Application software,Navigation,Hardware,Surgery,Meteorology,Weather forecasting,Geology",
    "Authors": [
      "Ricardo S. Avila",
      "Lisa Sobierajski",
      "Arie E Kaufman"
    ]
  },
  {
    "Paper_ID": 346340.0,
    "Title": "VolVis: a diversified volume visualization system",
    "Date_Published": 1994.0,
    "Abstract": "VolVis is a diversified, easy to use, extensible, high performance, and portable volume visualization system for scientists and engineers as well as for visualization developers and researchers. VolVis accepts as input 3D scalar volumetric data as well as 3D volume-sampled and classical geometric models. Interaction with the data is controlled by a variety of 3D input devices in an input device-independent environment. VolVis output includes navigation preview, static images, and animation sequences. A variety of volume rendering algorithms are supported ranging from fast rough approximations, to compression-domain rendering, to accurate volumetric ray tracing and radiosity, and irregular grid rendering.<\n<ETX xmlns:mml=\"http://www.w3.org/1998/Math/MathML\" xmlns:xlink=\"http://www.w3.org/1999/xlink\">&gt;</ETX>",
    "Author_Keywords": null,
    "Track": "Vis",
    "Award_Type": null,
    "Award": false,
    "Number_Authors": 8.0,
    "Number_references": 15.0,
    "Times_Cited": 32.0,
    "IEEE_Keywords": "Data visualization,Solid modeling,Rendering (computer graphics),Ray tracing,Workstations,Graphics,Pipelines,Data mining,Helium,Artificial intelligence",
    "Authors": [
      "Ricardo S. Avila",
      "Taosong He",
      "Lichan Hong",
      "Arie E Kaufman",
      "Hanspeter Pfister",
      "Claudio T. Silva",
      "Lisa Sobierajski",
      "Sidney Wang"
    ]
  },
  {
    "Paper_ID": 398900.0,
    "Title": "A climate simulation case study",
    "Date_Published": 1993.0,
    "Abstract": "A supercomputing-visualization facility for science and engineering applications was used for processing and visualizing supercomputer-generated data. This facility includes a vector-processing supercomputer, a graphics workstation, a general purpose workstation, a high-resolution color printer, a scanner, a film recorder, a video tape recorder, and a video laser disc recorder. The facility is using a network system to connect computers, workstations, and graphical input/output devices. The supercomputer generates time-dependent multivariate data using a global climate simulation model. Visualization software systems are used for visualizing these model-produced data. Visualization techniques including: iso-contouring, iso-surface generation, vectors and streamlines generation are used.<\n<ETX xmlns:mml=\"http://www.w3.org/1998/Math/MathML\" xmlns:xlink=\"http://www.w3.org/1999/xlink\">&gt;</ETX>",
    "Author_Keywords": null,
    "Track": "Vis",
    "Award_Type": null,
    "Award": false,
    "Number_Authors": 1.0,
    "Number_references": 4.0,
    "Times_Cited": 2.0,
    "IEEE_Keywords": "Data visualization,Workstations,Supercomputers,Data engineering,Application software,Computer graphics,Printers,Laser modes,Laser theory,Computer networks",
    "Authors": [
      "P.C. Chen"
    ]
  },
  {
    "Paper_ID": 663900.0,
    "Title": "Integrated volume compression and visualization",
    "Date_Published": 1997.0,
    "Abstract": "Volumetric data sets require enormous storage capacity even at moderate resolution levels. The excessive storage demands not only stress the capacity of the underlying storage and communications systems, but also seriously limit the speed of volume rendering due to data movement and manipulation. A novel volumetric data visualization scheme is proposed and implemented in this work that renders 2D images directly from compressed 3D data sets. The novelty of this algorithm is that rendering is performed on the compressed representation of the volumetric data without pre-decompression. As a result, the overheads associated with both data movement and rendering processing are significantly reduced. The proposed algorithm generalizes previously proposed whole-volume frequency-domain rendering schemes by first dividing the 3D data set into subcubes, transforming each subcube to a frequency-domain representation, and applying the Fourier projection theorem to produce the projected 2D images according to given viewing angles. Compared to the whole-volume approach, the subcube-based scheme not only achieves higher compression efficiency by exploiting local coherency, but also improves the quality of resultant rendering images because it approximates the occlusion effect on a subcube by subcube basis.",
    "Author_Keywords": null,
    "Track": "Vis",
    "Award_Type": null,
    "Award": false,
    "Number_Authors": 5.0,
    "Number_references": 16.0,
    "Times_Cited": 5.0,
    "IEEE_Keywords": "Image coding,Rendering (computer graphics),Data visualization,Fourier transforms,Nuclear magnetic resonance,Helium,Computer science,Stress,Communication systems,Frequency conversion",
    "Authors": [
      "Tzi-Cker Chiueh",
      "Chuan-Kai Yang",
      "Taosong He",
      "Hanspeter Pfister",
      "Arie E Kaufman"
    ]
  },
  {
    "Paper_ID": 1183764.0,
    "Title": "Interactive translucent volume rendering and procedural modeling",
    "Date_Published": 2002.0,
    "Abstract": "Direct volume rendering is a commonly used technique in visualization applications. Many of these applications require sophisticated shading models to capture subtle lighting effects and characteristics of volumetric data and materials. Many common objects and natural phenomena exhibit visual quality that cannot be captured using simple lighting models or cannot be solved at interactive rates using more sophisticated methods. We present a simple yet effective interactive shading model which captures volumetric light attenuation effects to produce volumetric shadows and the subtle appearance of translucency. We also present a technique for volume displacement or perturbation that allows realistic interactive modeling of high frequency detail for real and synthetic volumetric data.",
    "Author_Keywords": null,
    "Track": "Vis",
    "Award_Type": null,
    "Award": false,
    "Number_Authors": 4.0,
    "Number_references": 38.0,
    "Times_Cited": 40.0,
    "IEEE_Keywords": "Rendering (computer graphics),Data visualization,Light scattering,Application software,Clouds,Marine animals,Computed tomography,Optical attenuators,Computer graphics,Transfer functions",
    "Authors": [
      "Joe Kniss",
      "Simon Premoze",
      "Charles Hansen",
      "David S. Ebert"
    ]
  },
  {
    "Paper_ID": 1372188.0,
    "Title": "Physically based methods for tensor field visualization",
    "Date_Published": 2004.0,
    "Abstract": "The physical interpretation of mathematical features of tensor fields is highly application-specific. Existing visualization methods for tensor fields only cover a fraction of the broad application areas. We present a visualization method tailored specifically to the class of tensor field exhibiting properties similar to stress and strain tensors, which are commonly encountered in geomechanics. Our technique is a global method that represents the physical meaning of these tensor fields with their central features: regions of compression or expansion. The method is based on two steps: first, we define a positive definite metric, with the same topological structure as the tensor field; second, we visualize the resulting metric. The eigenvector fields are represented using a texture-based approach resembling line integral convolution (LIC) methods. The eigenvalues of the metric are encoded in free parameters of the texture definition. Our method supports an intuitive distinction between positive and negative eigenvalues. We have applied our method to synthetic and some standard data sets, and \"real\" data from earth science and mechanical engineering application.",
    "Author_Keywords": "tensors field,stress tensor,strain tensor,LIC",
    "Track": "Vis",
    "Award_Type": null,
    "Award": false,
    "Number_Authors": 6.0,
    "Number_references": 19.0,
    "Times_Cited": 30.0,
    "IEEE_Keywords": "Tensile stress,Visualization,Eigenvalues and eigenfunctions,Capacitive sensors,Convolution,Data engineering,Filters,Geoscience,Mechanical engineering,Application software",
    "Authors": [
      "Ingrid Hotz",
      "Louis Feng",
      "Hans Hagen",
      "Bernd Hamann",
      "Kenneth I. Joy",
      "B. Jeremic"
    ]
  },
  {
    "Paper_ID": 4376172.0,
    "Title": "Efficient Computation of Morse-Smale Complexes for Three-dimensional Scalar Functions",
    "Date_Published": 2007.0,
    "Abstract": "The Morse-Smale complex is an efficient representation of the gradient behavior of a scalar function, and critical points paired by the complex identify topological features and their importance. We present an algorithm that constructs the Morse-Smale complex in a series of sweeps through the data, identifying various components of the complex in a consistent manner. All components of the complex, both geometric and topological, are computed, providing a complete decomposition of the domain. Efficiency is maintained by representing the geometry of the complex in terms of point sets.",
    "Author_Keywords": "Morse theory,Morse-Smale complexes,computational topology,multiresolution,simplification,feature detection,3D scalar fields",
    "Track": "Vis",
    "Award_Type": null,
    "Award": false,
    "Number_Authors": 4.0,
    "Number_references": 30.0,
    "Times_Cited": 57.0,
    "IEEE_Keywords": "Isosurfaces,Topology,Computer science,Tree graphs,Surface topography,Data analysis,Data visualization,Data structures,Geometry,Computer vision",
    "Authors": [
      "A. Gyulassy",
      "Vijay Natarajan",
      "Valerio Pascucci",
      "Bernd Hamann"
    ]
  }
]

export default function DisplayRecommendationTable() {
  const styles = {
    tableContainerStyles: {
      height: `${window.innerHeight * 0.84}px`,
      overflowY: 'auto',
    },
  }

  const columns = React.useMemo(
    () => [
      {
        accessorKey: 'Title', //access nested data with dot notation
        enableColumnOrdering: true,
        header: 'Paper Title',
      },
      {
        accessorKey: 'Authors',
        enableColumnOrdering: true,
        header: 'Authors',
      },
      {
        accessorKey: 'Times_Cited', //normal accessorKey
        enableColumnOrdering: true,
        header: 'Citations No.',
      },
      {
        accessorKey: 'IEEE_Keywords',
        enableColumnOrdering: true,
        header: 'Keywords',
      },
      {
        accessorKey: 'Date_Published',
        enableColumnOrdering: true,
        header: 'Year',
      },
    ],
    [],
  );

  const [bulbIndex, setBulbIndex] = React.useState(-1);


  return (
    <div style={styles.tableContainerStyles}>
      <MaterialReactTable
        columns={columns}
        data={paperData}
        enableColumnOrdering
        enableColumnResizing
        enableStickyHeader
        enableStickyFooter
        enableRowActions
        enableBottomToolbar={false}
        renderDetailPanel={({ row }) => (
          <Box
            sx={{
              display: 'grid',
              margin: 'auto',
              width: '100%',
            }}
          >
            <Typography sx={{ mb: 2 }}>Title: {row.original.Title}</Typography>
            <Typography sx={{ mb: 2 }}>Authors: {row.original.Authors}</Typography>
            <Typography sx={{ mb: 2 }}>Keywords: {row.original.IEEE_Keywords}</Typography>
            <Typography sx={{ mb: 2 }}>Abstract: {row.original.Abstract}</Typography>
            <Typography sx={{ mb: 2 }}>Number of references: {row.original.Number_references}</Typography>
            <Typography sx={{ mb: 2 }}>Number of citations: {row.original.Times_Cited}</Typography>
          </Box>
        )}
        renderRowActions={(row) => (
          <Box sx={{ display: 'flex', flexWrap: 'nowrap', gap: '8px' }}>
            <IconButton
              color="#000000"
              onClick={() => {
                if (bulbIndex !== -1) {
                  if (bulbIndex !== row.row.id) {
                    setBulbIndex(row.row.id)
                  } else {
                    setBulbIndex(-1)
                  }
                } else {
                  setBulbIndex(row.row.id)
                }
              }}
            >
              {bulbIndex === row.row.id ? (
                <LightBulbIcon style={{ color: "#FFD700" }} />
              ) : (
                <LightBulbIcon />
              )}
            </IconButton>
          </Box>
        )}
      />
    </div>
  );
}
